# Logo (Font Awesome Class)
fa_logo: fa-gg

# Header
menu:
  Home - 首页: /
  Tags - 标签: /tags
  Archives - 归档: /archives
  Categories - 分类: /categories
  +: /#menu
  E-Nav - 生态导航: ../page/e-nav
  # WD-Event - 凌辰大事件: ../page/wd-event
  

# Default post title
default_post_title: 

# Archive Date Format
archive_date_format: MMM YYYY

# Comments.
comments:
  # Disqus comments
  disqus_shortname: weedust

# Google Analytics Tracking ID
google_analytics: UA-104966508-1

# Social Accounts
github_url: https://github.com/ldc4
email_url: 544420314@qq.com


# Footer About Text
footer_about: "天道酬勤，越努力，越幸运！<br />克己自律，逐梦前行！<br />愿一如既往！"

# Footer Copyright Line
footer_copyright: "@weedustzhao. All right reserved"

